#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qlsv")]
	public partial class Qlsv : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTbl_lophoc(Tbl_lophoc instance);
    partial void UpdateTbl_lophoc(Tbl_lophoc instance);
    partial void DeleteTbl_lophoc(Tbl_lophoc instance);
    partial void InsertTbl_sinhviens(Tbl_sinhviens instance);
    partial void UpdateTbl_sinhviens(Tbl_sinhviens instance);
    partial void DeleteTbl_sinhviens(Tbl_sinhviens instance);
    #endregion
		
		public Qlsv(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Qlsv(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Qlsv(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Qlsv(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_lophoc> Tbl_lophoc
		{
			get
			{
				return this.GetTable<Tbl_lophoc>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_sinhviens> Tbl_sinhviens
		{
			get
			{
				return this.GetTable<Tbl_sinhviens>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_lophoc")]
	public partial class Tbl_lophoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Malop;
		
		private string _Tenlop;
		
		private string _Ghichu;
		
		private EntitySet<Tbl_sinhviens> _Tbl_sinhviens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMalopChanging(string value);
    partial void OnMalopChanged();
    partial void OnTenlopChanging(string value);
    partial void OnTenlopChanged();
    partial void OnGhichuChanging(string value);
    partial void OnGhichuChanged();
    #endregion
		
		public Tbl_lophoc()
		{
			this._Tbl_sinhviens = new EntitySet<Tbl_sinhviens>(new Action<Tbl_sinhviens>(this.attach_Tbl_sinhviens), new Action<Tbl_sinhviens>(this.detach_Tbl_sinhviens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="malop", Storage="_Malop", DbType="VarChar(20)")]
		public string Malop
		{
			get
			{
				return this._Malop;
			}
			set
			{
				if ((this._Malop != value))
				{
					this.OnMalopChanging(value);
					this.SendPropertyChanging();
					this._Malop = value;
					this.SendPropertyChanged("Malop");
					this.OnMalopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tenlop", Storage="_Tenlop", DbType="NVarChar(100)")]
		public string Tenlop
		{
			get
			{
				return this._Tenlop;
			}
			set
			{
				if ((this._Tenlop != value))
				{
					this.OnTenlopChanging(value);
					this.SendPropertyChanging();
					this._Tenlop = value;
					this.SendPropertyChanged("Tenlop");
					this.OnTenlopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ghichu", Storage="_Ghichu", DbType="NVarChar(255)")]
		public string Ghichu
		{
			get
			{
				return this._Ghichu;
			}
			set
			{
				if ((this._Ghichu != value))
				{
					this.OnGhichuChanging(value);
					this.SendPropertyChanging();
					this._Ghichu = value;
					this.SendPropertyChanged("Ghichu");
					this.OnGhichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_lophoc_Tbl_sinhviens", Storage="_Tbl_sinhviens", ThisKey="Malop", OtherKey="Malop")]
		public EntitySet<Tbl_sinhviens> Tbl_sinhviens
		{
			get
			{
				return this._Tbl_sinhviens;
			}
			set
			{
				this._Tbl_sinhviens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_sinhviens(Tbl_sinhviens entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_lophoc = this;
		}
		
		private void detach_Tbl_sinhviens(Tbl_sinhviens entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_lophoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_sinhviens")]
	public partial class Tbl_sinhviens : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Hoten;
		
		private string _Gioitinh;
		
		private System.Nullable<System.DateTime> _Ngaysinh;
		
		private string _Malop;
		
		private EntityRef<Tbl_lophoc> _Tbl_lophoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnGioitinhChanging(string value);
    partial void OnGioitinhChanged();
    partial void OnNgaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaysinhChanged();
    partial void OnMalopChanging(string value);
    partial void OnMalopChanged();
    #endregion
		
		public Tbl_sinhviens()
		{
			this._Tbl_lophoc = default(EntityRef<Tbl_lophoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="hoten", Storage="_Hoten", DbType="NVarChar(100)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="gioitinh", Storage="_Gioitinh", DbType="NVarChar(10)")]
		public string Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ngaysinh", Storage="_Ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this.OnNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._Ngaysinh = value;
					this.SendPropertyChanged("Ngaysinh");
					this.OnNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="malop", Storage="_Malop", DbType="VarChar(20)")]
		public string Malop
		{
			get
			{
				return this._Malop;
			}
			set
			{
				if ((this._Malop != value))
				{
					this.OnMalopChanging(value);
					this.SendPropertyChanging();
					this._Malop = value;
					this.SendPropertyChanged("Malop");
					this.OnMalopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_lophoc_Tbl_sinhviens", Storage="_Tbl_lophoc", ThisKey="Malop", OtherKey="Malop", IsForeignKey=true)]
		public Tbl_lophoc Tbl_lophoc
		{
			get
			{
				return this._Tbl_lophoc.Entity;
			}
			set
			{
				Tbl_lophoc previousValue = this._Tbl_lophoc.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_lophoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_lophoc.Entity = null;
						previousValue.Tbl_sinhviens.Remove(this);
					}
					this._Tbl_lophoc.Entity = value;
					if ((value != null))
					{
						value.Tbl_sinhviens.Add(this);
						this._Malop = value.Malop;
					}
					else
					{
						this._Malop = default(string);
					}
					this.SendPropertyChanged("Tbl_lophoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
